# Generated by Django 5.1.2 on 2025-02-18 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6b2771fc-c378-4c09-a225-d26194e3ad77'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('abf97493-a0e6-4d19-848f-aa53079f5ba8'), primary_key=True, serialize=False),
        ),
    ]
