services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    env_file: .env
    ports:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: ..
    container_name: messaging_app
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env

volumes:
  db_data: