import mysql.connector
from mysql.connector import Error
from config import Config
import sys

def stream_users_in_batches(batch_size):
    connection = None
    try:
        connection = mysql.connector.connect(
            host='localhost',
            user='airbnb_sys',
            password=Config.PASSWORD,
            database='ALX_prodev'
        )
        cursor = connection.cursor(dictionary=True)

        cursor.execute("SELECT * FROM user_data")
        while True:
            rows = cursor.fetchmany(batch_size)
            if not rows:
                break
            yield rows
    except Error as e:
        print(e)
    finally: 
        if connection:
            connection.close()

def batch_processing(batch_size):
    for batch in stream_users_in_batches(batch_size):
        filtered_users = [user for user in batch if user['age'] > 25]
        yield filtered_users


# Run the batch processing function
if __name__ == "__main__":
    try:
        # Explicitly iterate through the batches generated by batch_processing
        for filtered_batch in batch_processing(50):
            # Do something with the filtered data, e.g., print or further process it
            pass  # This is where you can process the filtered data
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)