# Generated by Django 5.1.2 on 2025-01-03 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('97b1732c-5a72-4123-83a1-408265f3fe49'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('84782fda-2a6b-4444-b2ce-56d9820638d5'), primary_key=True, serialize=False),
        ),
    ]
