# Generated by Django 5.1.2 on 2025-02-18 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('253d4fd6-d09c-4531-8d5f-1c785ed47bae'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c9e22de0-f0a2-4718-859a-5f074321609e'), primary_key=True, serialize=False),
        ),
    ]
