# Generated by Django 5.1.2 on 2025-02-18 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('89b94771-5a46-4425-9c59-b1ff26c20672'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('03975f7b-650e-4d6a-ae6b-a5a9a3b7623b'), primary_key=True, serialize=False),
        ),
    ]
