# Generated by Django 5.1.2 on 2025-02-18 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('63ac2007-dfbe-4d7e-bf3f-27545c6d0d3a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('d7d67f42-2703-4b5d-9306-8df39f67b787'), primary_key=True, serialize=False),
        ),
    ]
