# Generated by Django 5.1.2 on 2025-02-18 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('f1d74963-372c-4665-9734-ac1f036e671d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('269b7d23-a217-4fc8-b8a1-e133ec1e152e'), primary_key=True, serialize=False),
        ),
    ]
