# Generated by Django 5.1.2 on 2025-02-18 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('2b7180ba-2aa2-4a80-9eac-53f65e55d694'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('cc9dfe9a-43ea-4bfe-92ea-3797746ffce7'), primary_key=True, serialize=False),
        ),
    ]
