# Generated by Django 5.1.2 on 2025-02-18 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0914eba2-a009-4a25-b9ee-8a58b8568a8c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c25861c7-a80e-4074-a9e5-b0c88755c4fc'), primary_key=True, serialize=False),
        ),
    ]
